"""empty message

Revision ID: 504604ad802f
Revises: 53abc688e41b
Create Date: 2023-06-02 21:28:02.313386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '504604ad802f'
down_revision = '53abc688e41b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('content')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('favorite_color')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_color', sa.VARCHAR(length=90), nullable=True))

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
