"""added full_name

Revision ID: 53abc688e41b
Revises: 27205fdb0266
Create Date: 2023-05-30 22:45:08.499755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53abc688e41b'
down_revision = '27205fdb0266'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=90), nullable=False))
        batch_op.create_unique_constraint(None, ['full_name'])
        batch_op.drop_column('favorite_color')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_color', sa.VARCHAR(length=90), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
